# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  browser-bookmarks-nvim = {
    pname = "browser-bookmarks-nvim";
    version = "06cfcb53bf3012792f36eb8eb6cd08f782c9b329";
    src = fetchFromGitHub {
      owner = "dhruvmanila";
      repo = "browser-bookmarks.nvim";
      rev = "06cfcb53bf3012792f36eb8eb6cd08f782c9b329";
      fetchSubmodules = false;
      sha256 = "sha256-eoNC0JgaqFh1zb/Sf13i90rKepz9mz6achOYjROU8Es=";
    };
    date = "2024-03-26";
  };
  commander-nvim = {
    pname = "commander-nvim";
    version = "84101e8eb1613a72bbdec655b734f891d8a00694";
    src = fetchFromGitHub {
      owner = "FeiyouG";
      repo = "commander.nvim";
      rev = "84101e8eb1613a72bbdec655b734f891d8a00694";
      fetchSubmodules = false;
      sha256 = "sha256-eXOHR+lwHVJze6jvFuDlvcUtFSpV8EJqlWvXLRWeCNI=";
    };
    date = "2024-06-07";
  };
  d2-vim = {
    pname = "d2-vim";
    version = "cb3eb7fcb1a2d45c4304bf2e91077d787b724a39";
    src = fetchFromGitHub {
      owner = "terrastruct";
      repo = "d2-vim";
      rev = "cb3eb7fcb1a2d45c4304bf2e91077d787b724a39";
      fetchSubmodules = false;
      sha256 = "sha256-HmDQfOIoSV93wqRe7O4FPuHEmAxwoP1+Ut+sKhB62jA=";
    };
    date = "2025-08-18";
  };
  easypick-nvim = {
    pname = "easypick-nvim";
    version = "e623b38a0d8fb96446dd8dd3f38ccb545e1810a8";
    src = fetchFromGitHub {
      owner = "axkirillov";
      repo = "easypick.nvim";
      rev = "e623b38a0d8fb96446dd8dd3f38ccb545e1810a8";
      fetchSubmodules = false;
      sha256 = "sha256-gIx5yOwqPyg6hySiJPf1dtt250qFDBVa8pkjpncf0V8=";
    };
    date = "2025-04-26";
  };
  fm-nvim = {
    pname = "fm-nvim";
    version = "8e6a77049330e7c797eb9e63affd75eb796fe75e";
    src = fetchFromGitHub {
      owner = "is0n";
      repo = "fm-nvim";
      rev = "8e6a77049330e7c797eb9e63affd75eb796fe75e";
      fetchSubmodules = false;
      sha256 = "sha256-I29p08P4Wh/LLTDZIQ2TkYy5Kdj0G8loU6k3eFM+iVE=";
    };
    date = "2022-10-10";
  };
  gitlinker-nvim = {
    pname = "gitlinker-nvim";
    version = "d7adb5e4ba5bab4fd443a3f4c46af3f4c864685d";
    src = fetchFromGitHub {
      owner = "linrongbin16";
      repo = "gitlinker.nvim";
      rev = "d7adb5e4ba5bab4fd443a3f4c46af3f4c864685d";
      fetchSubmodules = false;
      sha256 = "sha256-jWoxp/Ux/fb7Diu5b3UaoTKv9a4WOlV9WLQ9TYUjJoI=";
    };
    date = "2026-04-07";
  };
  magma-nvim = {
    pname = "magma-nvim";
    version = "ff3deba8a879806a51c005e50782130246143d06";
    src = fetchFromGitHub {
      owner = "dccsillag";
      repo = "magma-nvim";
      rev = "ff3deba8a879806a51c005e50782130246143d06";
      fetchSubmodules = false;
      sha256 = "sha256-IrMR57gk9iCk73esHO24KZeep9VrlkV5sOC4PzGexyo=";
    };
    date = "2023-07-08";
  };
  middleclass-nvim = {
    pname = "middleclass-nvim";
    version = "359f0e2742f51ca77801b513ec91eb9029de8de4";
    src = fetchFromGitHub {
      owner = "kikito";
      repo = "middleclass";
      rev = "359f0e2742f51ca77801b513ec91eb9029de8de4";
      fetchSubmodules = false;
      sha256 = "sha256-31KF7rUPyO5mnMKRixvPpqdhNqnzx9ZC8zvNga+rdy0=";
    };
    date = "2025-11-03";
  };
  neozoom-nvim = {
    pname = "neozoom-nvim";
    version = "c97a0197548c1e9b559e4fa41ab3f7782c93e613";
    src = fetchFromGitHub {
      owner = "nyngwang";
      repo = "NeoZoom.lua";
      rev = "c97a0197548c1e9b559e4fa41ab3f7782c93e613";
      fetchSubmodules = false;
      sha256 = "sha256-O5ovnf0tYbyGKC0OzE05WNRv84mVTocfh0lKk3+cSsY=";
    };
    date = "2024-04-18";
  };
  nvim-devdocs = {
    pname = "nvim-devdocs";
    version = "1ab982d3e069d191d9157b897c8b70cf48b7f77a";
    src = fetchFromGitHub {
      owner = "luckasRanarison";
      repo = "nvim-devdocs";
      rev = "1ab982d3e069d191d9157b897c8b70cf48b7f77a";
      fetchSubmodules = false;
      sha256 = "sha256-NvxsUAl+FKrT60xmrVBh/EVLuWrGaLWWwFsWYrr7QKc=";
    };
    date = "2024-04-11";
  };
  nvim-guess-indent = {
    pname = "nvim-guess-indent";
    version = "84a4987ff36798c2fc1169cbaff67960aed9776f";
    src = fetchFromGitHub {
      owner = "NMAC427";
      repo = "guess-indent.nvim";
      rev = "84a4987ff36798c2fc1169cbaff67960aed9776f";
      fetchSubmodules = false;
      sha256 = "sha256-M/FkwCXXhojVFEcCuHo/GkuCCSX9GlVYHBUECSZxBjs=";
    };
    date = "2025-03-25";
  };
  nvim-telescope-hop = {
    pname = "nvim-telescope-hop";
    version = "337a1e9f08f972ebf7a7d26251577812ebaadc78";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-hop.nvim";
      rev = "337a1e9f08f972ebf7a7d26251577812ebaadc78";
      fetchSubmodules = false;
      sha256 = "sha256-OtCSjglHdXKj9EqnaTzw+4/L+op/lJ82CxlvxPLsee8=";
    };
    date = "2021-11-05";
  };
  one-small-step-for-vimkind-nvim = {
    pname = "one-small-step-for-vimkind-nvim";
    version = "1af6ffb9b5229a856e8090fa2f690e0931a5aace";
    src = fetchFromGitHub {
      owner = "jbyuki";
      repo = "one-small-step-for-vimkind";
      rev = "1af6ffb9b5229a856e8090fa2f690e0931a5aace";
      fetchSubmodules = false;
      sha256 = "sha256-IqyNgMf8hH2KpRY8gTrqREMCZwMNfDRdH/joqhGhjxI=";
    };
    date = "2026-01-12";
  };
  portal-nvim = {
    pname = "portal-nvim";
    version = "77d9d53fec945bfa407d5fd7120f1b4f117450ed";
    src = fetchFromGitHub {
      owner = "cbochs";
      repo = "portal.nvim";
      rev = "77d9d53fec945bfa407d5fd7120f1b4f117450ed";
      fetchSubmodules = false;
      sha256 = "sha256-QCdyJ5in3Dm4IVlBUtbGWRZxl87gKHhRiGmZcIGEHm0=";
    };
    date = "2024-04-01";
  };
  quickselect-nvim = {
    pname = "quickselect-nvim";
    version = "3e98669803f37957ebc1092eb17a6ec2393127cb";
    src = fetchFromGitHub {
      owner = "ausgefuchster";
      repo = "quickselect.nvim";
      rev = "3e98669803f37957ebc1092eb17a6ec2393127cb";
      fetchSubmodules = false;
      sha256 = "sha256-1GugI92ZhlUl7Dp9UcIx7/zH0AdNJg6vmhaGCe8xIa0=";
    };
    date = "2024-12-21";
  };
  replua-nvim = {
    pname = "replua-nvim";
    version = "8ed56f58aaec2d22e61907c46fbbc2a1d15b2ffd";
    src = fetchFromGitHub {
      owner = "mghaight";
      repo = "replua.nvim";
      rev = "8ed56f58aaec2d22e61907c46fbbc2a1d15b2ffd";
      fetchSubmodules = false;
      sha256 = "sha256-gptddyPsSCjWRG/YIN/LBVKgF0XoIUcblaj4NTfL2zA=";
    };
    date = "2025-10-21";
  };
  sessions-nvim = {
    pname = "sessions-nvim";
    version = "a67a29ef442a7bdcf99d96576190c47145dad65e";
    src = fetchFromGitHub {
      owner = "natecraddock";
      repo = "sessions.nvim";
      rev = "a67a29ef442a7bdcf99d96576190c47145dad65e";
      fetchSubmodules = false;
      sha256 = "sha256-O3wsxUiNUPyAYt1v47xL1eBoFHSskxM6VQ0sIEFXaW0=";
    };
    date = "2025-11-30";
  };
  telescope-all-recent = {
    pname = "telescope-all-recent";
    version = "e437f60ea468268e49ffdc0c9ed7c5ba384e63cf";
    src = fetchFromGitHub {
      owner = "prochri";
      repo = "telescope-all-recent.nvim";
      rev = "e437f60ea468268e49ffdc0c9ed7c5ba384e63cf";
      fetchSubmodules = false;
      sha256 = "sha256-Dq0eahhshmgdrof9eG3rBNm06UCCsjMYNkBs4KE/cEQ=";
    };
    date = "2025-03-19";
  };
  telescope-changes = {
    pname = "telescope-changes";
    version = "7ed65f3698be4b5f7a9cdeb88a657bfa866dcb3c";
    src = fetchFromGitHub {
      owner = "LinArcX";
      repo = "telescope-changes.nvim";
      rev = "7ed65f3698be4b5f7a9cdeb88a657bfa866dcb3c";
      fetchSubmodules = false;
      sha256 = "sha256-HXP/Dc8u+1BAtR1xOsUaqJAzyXrcP2691BCJ86F4fp8=";
    };
    date = "2022-03-26";
  };
  telescope-env = {
    pname = "telescope-env";
    version = "00a703cc7b713cdda0a981d88fddf3ce25502af5";
    src = fetchFromGitHub {
      owner = "LinArcX";
      repo = "telescope-env.nvim";
      rev = "00a703cc7b713cdda0a981d88fddf3ce25502af5";
      fetchSubmodules = false;
      sha256 = "sha256-gwpheCuMOSfRf9A5nHAOrb0S6GHQE3we9QAa6ri2XaQ=";
    };
    date = "2022-12-15";
  };
  telescope-gitsigns-nvim = {
    pname = "telescope-gitsigns-nvim";
    version = "e568da4b8b6da800bd9274f7b509c0da81fc8615";
    src = fetchFromGitHub {
      owner = "radyz";
      repo = "telescope-gitsigns";
      rev = "e568da4b8b6da800bd9274f7b509c0da81fc8615";
      fetchSubmodules = false;
      sha256 = "sha256-ULmo84ameJ4D62wrvsb+9YCUKGhOYpHvgIffGKF0Vo8=";
    };
    date = "2023-10-30";
  };
  telescope-lazy-nvim = {
    pname = "telescope-lazy-nvim";
    version = "0f017103b2946fc0c14498f769ea0ec8ba964cd1";
    src = fetchFromGitHub {
      owner = "tsakirist";
      repo = "telescope-lazy.nvim";
      rev = "0f017103b2946fc0c14498f769ea0ec8ba964cd1";
      fetchSubmodules = false;
      sha256 = "sha256-h7SK6BowB2SsYMbdWeTrfLSnhDYSeJ667hEwa2FWqi8=";
    };
    date = "2025-10-10";
  };
  telescope-live-grep-args-nvim = {
    pname = "telescope-live-grep-args-nvim";
    version = "53e9df55b3651dd7cf77e172f1e8c9a17407acca";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-live-grep-args.nvim";
      rev = "53e9df55b3651dd7cf77e172f1e8c9a17407acca";
      fetchSubmodules = false;
      sha256 = "sha256-kGGVegympVG4lzJ0zdFjsjiioy0gSQbJuENjll3jNlQ=";
    };
    date = "2026-04-08";
  };
  telescope-luasnip = {
    pname = "telescope-luasnip";
    version = "07a2a2936a7557404c782dba021ac0a03165b343";
    src = fetchFromGitHub {
      owner = "benfowler";
      repo = "telescope-luasnip.nvim";
      rev = "07a2a2936a7557404c782dba021ac0a03165b343";
      fetchSubmodules = false;
      sha256 = "sha256-9XsV2hPjt05q+y5FiSbKYYXnznDKYOsDwsVmfskYd3M=";
    };
    date = "2024-12-14";
  };
  telescope-menufacture = {
    pname = "telescope-menufacture";
    version = "751aca3f022039874790024b3cf25d643e335612";
    src = fetchFromGitHub {
      owner = "molecule-man";
      repo = "telescope-menufacture";
      rev = "751aca3f022039874790024b3cf25d643e335612";
      fetchSubmodules = false;
      sha256 = "sha256-KgQTFVIab6bAtZ1I67IMrk8qxKWWfiUgGDX72n1jJsc=";
    };
    date = "2025-01-13";
  };
  telescope-tabs = {
    pname = "telescope-tabs";
    version = "62c127346c04c698c0cbd1c1ba945609a0ad10db";
    src = fetchFromGitHub {
      owner = "LukasPietzschmann";
      repo = "telescope-tabs";
      rev = "62c127346c04c698c0cbd1c1ba945609a0ad10db";
      fetchSubmodules = false;
      sha256 = "sha256-WIuY25GFqhVV5kD/2BYA1f5qniS0xQJ9iM2/2+6N2Iw=";
    };
    date = "2026-04-04";
  };
  telescope-undo = {
    pname = "telescope-undo";
    version = "928d0c2dc9606e01e2cc547196f48d2eaecf58e5";
    src = fetchFromGitHub {
      owner = "debugloop";
      repo = "telescope-undo.nvim";
      rev = "928d0c2dc9606e01e2cc547196f48d2eaecf58e5";
      fetchSubmodules = false;
      sha256 = "sha256-KKCBr5l6U2OoJ/rVkMP7pVeO5M6phx2MOrxc5yIn6L4=";
    };
    date = "2025-01-31";
  };
  terminal-nvim = {
    pname = "terminal-nvim";
    version = "2bd1545caf89d075b6bc2a1a5c56ff177edcf3f6";
    src = fetchFromGitHub {
      owner = "rebelot";
      repo = "terminal.nvim";
      rev = "2bd1545caf89d075b6bc2a1a5c56ff177edcf3f6";
      fetchSubmodules = false;
      sha256 = "sha256-L+BNITHwcPVJBzeIDWl4+S+jQPnmLrwQ6UbimTfMZfk=";
    };
    date = "2025-10-01";
  };
  tree-sitter-d2 = {
    pname = "tree-sitter-d2";
    version = "200434618a6bede20ebd4982aa4d4f1edeb0b5c1";
    src = fetchFromGitHub {
      owner = "ravsii";
      repo = "tree-sitter-d2";
      rev = "200434618a6bede20ebd4982aa4d4f1edeb0b5c1";
      fetchSubmodules = false;
      sha256 = "sha256-xN6yb7amTu61E8dFHB5Vrv52FOZUKOh3u5zfOIao7rQ=";
    };
    date = "2026-04-10";
  };
  vim-doge = {
    pname = "vim-doge";
    version = "03a84072ef21b205237c77986c78914395d646c3";
    src = fetchFromGitHub {
      owner = "kkoomen";
      repo = "vim-doge";
      rev = "03a84072ef21b205237c77986c78914395d646c3";
      fetchSubmodules = false;
      sha256 = "sha256-MlyXMPLdyZ+TjLHHCEadh9jIACtfjbMwV1VXKD5QYXU=";
    };
    date = "2025-04-06";
  };
}
